replicaCount: 1

image:
  repository: rishikkk/devops-app
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: false

env:
  APP_ENV: "dev"
  APP_VERSION: "1.0.0"
